name: hsi_env
channels:
  - anaconda
  - defaults
dependencies:
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - keras-gpu=2.4.3
  - numpy=1.19.1
  - pip=20.1.1
  - python=3.7.7
  - scikit-learn=0.23.1
  - tensorflow=2.2.0
  - pip:
    - keras-preprocessing==1.1.2
    - opt-einsum==3.3.0
    - protobuf==3.12.4
    - pyasn1-modules==0.2.8
    - pyyaml==5.3.1
    - scipy==1.4.1
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.7.0
    - termcolor==1.1.0

